cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'


brew 'autojump'
brew 'imagemagick'
brew 'coreutils'
brew 'libgit2'
brew 'mackup'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'unrar'
brew 'wget'
brew 'pyenv'

cask '1password'
cask 'atom'
cask 'firefox'
cask 'garmin-express'
cask 'google-chrome'
cask 'alfred'
cask 'qlmarkdown'
